#!/bin/sh

# Make sure everything is development forever
export NODE_ENV=development

set -e

cd "$(dirname "$0")/.."

echo "==> Installing gem dependencies…"
bundle check --path vendor/gems 2>&1 >/dev/null || {
  bundle install --path vendor/gems --quiet --without production
}

echo "==> Installing npm dependencies…"
npm install
