[[_hacking]]
== Hacking Atom

Now it's time to come to the ``Hackable'' part of the Hackable Editor. As we've seen throughout the second section, a huge part of Atom is made up of bundled packages. If you wish to add some functionality to Atom, you have access to the same APIs and tools that the core features of Atom has. From the https://github.com/atom/tree-view[tree view] to the https://github.com/atom/command-palette[command palette] to https://github.com/atom/find-and-replace[find and replace] functionality, even the most core features of Atom are implemented as packages.

In this chapter, we're going to learn how to extend the functionality of Atom through writing packages. This will be everything from new user interfaces to new language grammars to new themes. We'll learn this by writing a series of increasingly complex packages together, introducing you to new APIs and tools and techniques as we need them.

If you're looking for an example using a specific API or feature, you can skip to the end of the chapter where we've indexed all the examples that way.

include::sections/01-tools.asciidoc[]

include::sections/02-init-file.asciidoc[]

include::sections/03-a-basic-package.asciidoc[]

include::sections/04-modify-buffer.asciidoc[]

include::sections/05-themes.asciidoc[]

include::sections/06-iconography.asciidoc[]

include::sections/A01-debugging.asciidoc[]

include::sections/A02-writing-specs.asciidoc[]

include::sections/A03-textmate.asciidoc[]

=== Summary

( List of topics we covered / appendix? )

Summary.
